QT += core
QT -= gui

CONFIG += c++

TARGET = ros_test
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += main.cpp \
    ros_lib/duration.cpp \
    ros_lib/time.cpp \
    ros_lib/WindowsSocket.cpp

LIBS += -lws2_32

HEADERS += \
    ros_lib/actionlib/TestAction.h \
    ros_lib/actionlib/TestActionFeedback.h \
    ros_lib/actionlib/TestActionGoal.h \
    ros_lib/actionlib/TestActionResult.h \
    ros_lib/actionlib/TestFeedback.h \
    ros_lib/actionlib/TestGoal.h \
    ros_lib/actionlib/TestRequestAction.h \
    ros_lib/actionlib/TestRequestActionFeedback.h \
    ros_lib/actionlib/TestRequestActionGoal.h \
    ros_lib/actionlib/TestRequestActionResult.h \
    ros_lib/actionlib/TestRequestFeedback.h \
    ros_lib/actionlib/TestRequestGoal.h \
    ros_lib/actionlib/TestRequestResult.h \
    ros_lib/actionlib/TestResult.h \
    ros_lib/actionlib/TwoIntsAction.h \
    ros_lib/actionlib/TwoIntsActionFeedback.h \
    ros_lib/actionlib/TwoIntsActionGoal.h \
    ros_lib/actionlib/TwoIntsActionResult.h \
    ros_lib/actionlib/TwoIntsFeedback.h \
    ros_lib/actionlib/TwoIntsGoal.h \
    ros_lib/actionlib/TwoIntsResult.h \
    ros_lib/actionlib_msgs/GoalID.h \
    ros_lib/actionlib_msgs/GoalStatus.h \
    ros_lib/actionlib_msgs/GoalStatusArray.h \
    ros_lib/actionlib_tutorials/AveragingAction.h \
    ros_lib/actionlib_tutorials/AveragingActionFeedback.h \
    ros_lib/actionlib_tutorials/AveragingActionGoal.h \
    ros_lib/actionlib_tutorials/AveragingActionResult.h \
    ros_lib/actionlib_tutorials/AveragingFeedback.h \
    ros_lib/actionlib_tutorials/AveragingGoal.h \
    ros_lib/actionlib_tutorials/AveragingResult.h \
    ros_lib/actionlib_tutorials/FibonacciAction.h \
    ros_lib/actionlib_tutorials/FibonacciActionFeedback.h \
    ros_lib/actionlib_tutorials/FibonacciActionGoal.h \
    ros_lib/actionlib_tutorials/FibonacciActionResult.h \
    ros_lib/actionlib_tutorials/FibonacciFeedback.h \
    ros_lib/actionlib_tutorials/FibonacciGoal.h \
    ros_lib/actionlib_tutorials/FibonacciResult.h \
    ros_lib/base_local_planner/Position2DInt.h \
    ros_lib/bond/Constants.h \
    ros_lib/bond/Status.h \
    ros_lib/capabilities/Capability.h \
    ros_lib/capabilities/CapabilityEvent.h \
    ros_lib/capabilities/CapabilitySpec.h \
    ros_lib/capabilities/EstablishBond.h \
    ros_lib/capabilities/FreeCapability.h \
    ros_lib/capabilities/GetCapabilitySpec.h \
    ros_lib/capabilities/GetCapabilitySpecs.h \
    ros_lib/capabilities/GetInterfaces.h \
    ros_lib/capabilities/GetNodeletManagerName.h \
    ros_lib/capabilities/GetProviders.h \
    ros_lib/capabilities/GetRemappings.h \
    ros_lib/capabilities/GetRunningCapabilities.h \
    ros_lib/capabilities/GetSemanticInterfaces.h \
    ros_lib/capabilities/Remapping.h \
    ros_lib/capabilities/RunningCapability.h \
    ros_lib/capabilities/StartCapability.h \
    ros_lib/capabilities/StopCapability.h \
    ros_lib/capabilities/UseCapability.h \
    ros_lib/concert_msgs/AllocateSoftware.h \
    ros_lib/concert_msgs/ConcertClient.h \
    ros_lib/concert_msgs/ConcertClients.h \
    ros_lib/concert_msgs/ConcertClientState.h \
    ros_lib/concert_msgs/ConductorGraph.h \
    ros_lib/concert_msgs/EnableService.h \
    ros_lib/concert_msgs/ErrorCodes.h \
    ros_lib/concert_msgs/LinkConnection.h \
    ros_lib/concert_msgs/LinkEdge.h \
    ros_lib/concert_msgs/LinkGraph.h \
    ros_lib/concert_msgs/LinkNode.h \
    ros_lib/concert_msgs/ServiceProfile.h \
    ros_lib/concert_msgs/Services.h \
    ros_lib/concert_msgs/SoftwareInstance.h \
    ros_lib/concert_msgs/SoftwareInstances.h \
    ros_lib/concert_msgs/SoftwareProfile.h \
    ros_lib/concert_msgs/SoftwareProfiles.h \
    ros_lib/concert_msgs/Strings.h \
    ros_lib/concert_msgs/UpdateServiceConfig.h \
    ros_lib/control_msgs/FollowJointTrajectoryAction.h \
    ros_lib/control_msgs/FollowJointTrajectoryActionFeedback.h \
    ros_lib/control_msgs/FollowJointTrajectoryActionGoal.h \
    ros_lib/control_msgs/FollowJointTrajectoryActionResult.h \
    ros_lib/control_msgs/FollowJointTrajectoryFeedback.h \
    ros_lib/control_msgs/FollowJointTrajectoryGoal.h \
    ros_lib/control_msgs/FollowJointTrajectoryResult.h \
    ros_lib/control_msgs/GripperCommand.h \
    ros_lib/control_msgs/GripperCommandAction.h \
    ros_lib/control_msgs/GripperCommandActionFeedback.h \
    ros_lib/control_msgs/GripperCommandActionGoal.h \
    ros_lib/control_msgs/GripperCommandActionResult.h \
    ros_lib/control_msgs/GripperCommandFeedback.h \
    ros_lib/control_msgs/GripperCommandGoal.h \
    ros_lib/control_msgs/GripperCommandResult.h \
    ros_lib/control_msgs/JointControllerState.h \
    ros_lib/control_msgs/JointTolerance.h \
    ros_lib/control_msgs/JointTrajectoryAction.h \
    ros_lib/control_msgs/JointTrajectoryActionFeedback.h \
    ros_lib/control_msgs/JointTrajectoryActionGoal.h \
    ros_lib/control_msgs/JointTrajectoryActionResult.h \
    ros_lib/control_msgs/JointTrajectoryControllerState.h \
    ros_lib/control_msgs/JointTrajectoryFeedback.h \
    ros_lib/control_msgs/JointTrajectoryGoal.h \
    ros_lib/control_msgs/JointTrajectoryResult.h \
    ros_lib/control_msgs/PointHeadAction.h \
    ros_lib/control_msgs/PointHeadActionFeedback.h \
    ros_lib/control_msgs/PointHeadActionGoal.h \
    ros_lib/control_msgs/PointHeadActionResult.h \
    ros_lib/control_msgs/PointHeadFeedback.h \
    ros_lib/control_msgs/PointHeadGoal.h \
    ros_lib/control_msgs/PointHeadResult.h \
    ros_lib/control_msgs/QueryCalibrationState.h \
    ros_lib/control_msgs/QueryTrajectoryState.h \
    ros_lib/control_msgs/SingleJointPositionAction.h \
    ros_lib/control_msgs/SingleJointPositionActionFeedback.h \
    ros_lib/control_msgs/SingleJointPositionActionGoal.h \
    ros_lib/control_msgs/SingleJointPositionActionResult.h \
    ros_lib/control_msgs/SingleJointPositionFeedback.h \
    ros_lib/control_msgs/SingleJointPositionGoal.h \
    ros_lib/control_msgs/SingleJointPositionResult.h \
    ros_lib/costmap_2d/VoxelGrid.h \
    ros_lib/create_node/BatteryState.h \
    ros_lib/create_node/Drive.h \
    ros_lib/create_node/RawTurtlebotSensorState.h \
    ros_lib/create_node/RoombaSensorState.h \
    ros_lib/create_node/SetDigitalOutputs.h \
    ros_lib/create_node/SetTurtlebotMode.h \
    ros_lib/create_node/Turtle.h \
    ros_lib/create_node/TurtlebotSensorState.h \
    ros_lib/diagnostic_msgs/AddDiagnostics.h \
    ros_lib/diagnostic_msgs/DiagnosticArray.h \
    ros_lib/diagnostic_msgs/DiagnosticStatus.h \
    ros_lib/diagnostic_msgs/KeyValue.h \
    ros_lib/diagnostic_msgs/SelfTest.h \
    ros_lib/driver_base/ConfigString.h \
    ros_lib/driver_base/ConfigValue.h \
    ros_lib/driver_base/SensorLevels.h \
    ros_lib/dynamic_reconfigure/BoolParameter.h \
    ros_lib/dynamic_reconfigure/Config.h \
    ros_lib/dynamic_reconfigure/ConfigDescription.h \
    ros_lib/dynamic_reconfigure/DoubleParameter.h \
    ros_lib/dynamic_reconfigure/Group.h \
    ros_lib/dynamic_reconfigure/GroupState.h \
    ros_lib/dynamic_reconfigure/IntParameter.h \
    ros_lib/dynamic_reconfigure/ParamDescription.h \
    ros_lib/dynamic_reconfigure/Reconfigure.h \
    ros_lib/dynamic_reconfigure/SensorLevels.h \
    ros_lib/dynamic_reconfigure/StrParameter.h \
    ros_lib/gateway_msgs/Advertise.h \
    ros_lib/gateway_msgs/AdvertiseAll.h \
    ros_lib/gateway_msgs/ConnectHub.h \
    ros_lib/gateway_msgs/ConnectionStatistics.h \
    ros_lib/gateway_msgs/ConnectionType.h \
    ros_lib/gateway_msgs/ErrorCodes.h \
    ros_lib/gateway_msgs/GatewayInfo.h \
    ros_lib/gateway_msgs/Remote.h \
    ros_lib/gateway_msgs/RemoteAll.h \
    ros_lib/gateway_msgs/RemoteGateway.h \
    ros_lib/gateway_msgs/RemoteGatewayInfo.h \
    ros_lib/gateway_msgs/RemoteRule.h \
    ros_lib/gateway_msgs/RemoteRuleWithStatus.h \
    ros_lib/gateway_msgs/Rule.h \
    ros_lib/gateway_msgs/SetWatcherPeriod.h \
    ros_lib/gazebo_msgs/ApplyBodyWrench.h \
    ros_lib/gazebo_msgs/ApplyJointEffort.h \
    ros_lib/gazebo_msgs/BodyRequest.h \
    ros_lib/gazebo_msgs/ContactsState.h \
    ros_lib/gazebo_msgs/ContactState.h \
    ros_lib/gazebo_msgs/DeleteModel.h \
    ros_lib/gazebo_msgs/GetJointProperties.h \
    ros_lib/gazebo_msgs/GetLinkProperties.h \
    ros_lib/gazebo_msgs/GetLinkState.h \
    ros_lib/gazebo_msgs/GetModelProperties.h \
    ros_lib/gazebo_msgs/GetModelState.h \
    ros_lib/gazebo_msgs/GetPhysicsProperties.h \
    ros_lib/gazebo_msgs/GetWorldProperties.h \
    ros_lib/gazebo_msgs/JointRequest.h \
    ros_lib/gazebo_msgs/LinkState.h \
    ros_lib/gazebo_msgs/LinkStates.h \
    ros_lib/gazebo_msgs/ModelState.h \
    ros_lib/gazebo_msgs/ModelStates.h \
    ros_lib/gazebo_msgs/ODEJointProperties.h \
    ros_lib/gazebo_msgs/ODEPhysics.h \
    ros_lib/gazebo_msgs/SetJointProperties.h \
    ros_lib/gazebo_msgs/SetJointTrajectory.h \
    ros_lib/gazebo_msgs/SetLinkProperties.h \
    ros_lib/gazebo_msgs/SetLinkState.h \
    ros_lib/gazebo_msgs/SetModelConfiguration.h \
    ros_lib/gazebo_msgs/SetModelState.h \
    ros_lib/gazebo_msgs/SetPhysicsProperties.h \
    ros_lib/gazebo_msgs/SpawnModel.h \
    ros_lib/gazebo_msgs/WorldState.h \
    ros_lib/geometry_msgs/Accel.h \
    ros_lib/geometry_msgs/AccelStamped.h \
    ros_lib/geometry_msgs/AccelWithCovariance.h \
    ros_lib/geometry_msgs/AccelWithCovarianceStamped.h \
    ros_lib/geometry_msgs/Inertia.h \
    ros_lib/geometry_msgs/InertiaStamped.h \
    ros_lib/geometry_msgs/Point.h \
    ros_lib/geometry_msgs/Point32.h \
    ros_lib/geometry_msgs/PointStamped.h \
    ros_lib/geometry_msgs/Polygon.h \
    ros_lib/geometry_msgs/PolygonStamped.h \
    ros_lib/geometry_msgs/Pose.h \
    ros_lib/geometry_msgs/Pose2D.h \
    ros_lib/geometry_msgs/PoseArray.h \
    ros_lib/geometry_msgs/PoseStamped.h \
    ros_lib/geometry_msgs/PoseWithCovariance.h \
    ros_lib/geometry_msgs/PoseWithCovarianceStamped.h \
    ros_lib/geometry_msgs/Quaternion.h \
    ros_lib/geometry_msgs/QuaternionStamped.h \
    ros_lib/geometry_msgs/Transform.h \
    ros_lib/geometry_msgs/TransformStamped.h \
    ros_lib/geometry_msgs/Twist.h \
    ros_lib/geometry_msgs/TwistStamped.h \
    ros_lib/geometry_msgs/TwistWithCovariance.h \
    ros_lib/geometry_msgs/TwistWithCovarianceStamped.h \
    ros_lib/geometry_msgs/Vector3.h \
    ros_lib/geometry_msgs/Vector3Stamped.h \
    ros_lib/geometry_msgs/Wrench.h \
    ros_lib/geometry_msgs/WrenchStamped.h \
    ros_lib/kobuki_msgs/AutoDockingAction.h \
    ros_lib/kobuki_msgs/AutoDockingActionFeedback.h \
    ros_lib/kobuki_msgs/AutoDockingActionGoal.h \
    ros_lib/kobuki_msgs/AutoDockingActionResult.h \
    ros_lib/kobuki_msgs/AutoDockingFeedback.h \
    ros_lib/kobuki_msgs/AutoDockingGoal.h \
    ros_lib/kobuki_msgs/AutoDockingResult.h \
    ros_lib/kobuki_msgs/BumperEvent.h \
    ros_lib/kobuki_msgs/ButtonEvent.h \
    ros_lib/kobuki_msgs/CliffEvent.h \
    ros_lib/kobuki_msgs/ControllerInfo.h \
    ros_lib/kobuki_msgs/DigitalInputEvent.h \
    ros_lib/kobuki_msgs/DigitalOutput.h \
    ros_lib/kobuki_msgs/DockInfraRed.h \
    ros_lib/kobuki_msgs/ExternalPower.h \
    ros_lib/kobuki_msgs/KeyboardInput.h \
    ros_lib/kobuki_msgs/Led.h \
    ros_lib/kobuki_msgs/MotorPower.h \
    ros_lib/kobuki_msgs/PowerSystemEvent.h \
    ros_lib/kobuki_msgs/RobotStateEvent.h \
    ros_lib/kobuki_msgs/ScanAngle.h \
    ros_lib/kobuki_msgs/SensorState.h \
    ros_lib/kobuki_msgs/Sound.h \
    ros_lib/kobuki_msgs/VersionInfo.h \
    ros_lib/kobuki_msgs/WheelDropEvent.h \
    ros_lib/map_msgs/GetMapROI.h \
    ros_lib/map_msgs/GetPointMap.h \
    ros_lib/map_msgs/GetPointMapROI.h \
    ros_lib/map_msgs/OccupancyGridUpdate.h \
    ros_lib/map_msgs/PointCloud2Update.h \
    ros_lib/map_msgs/ProjectedMap.h \
    ros_lib/map_msgs/ProjectedMapInfo.h \
    ros_lib/map_msgs/ProjectedMapsInfo.h \
    ros_lib/map_msgs/SaveMap.h \
    ros_lib/map_msgs/SetMapProjections.h \
    ros_lib/map_store/DeleteMap.h \
    ros_lib/map_store/ListMaps.h \
    ros_lib/map_store/MapListEntry.h \
    ros_lib/map_store/PublishMap.h \
    ros_lib/map_store/RenameMap.h \
    ros_lib/map_store/SaveMap.h \
    ros_lib/move_base_msgs/MoveBaseAction.h \
    ros_lib/move_base_msgs/MoveBaseActionFeedback.h \
    ros_lib/move_base_msgs/MoveBaseActionGoal.h \
    ros_lib/move_base_msgs/MoveBaseActionResult.h \
    ros_lib/move_base_msgs/MoveBaseFeedback.h \
    ros_lib/move_base_msgs/MoveBaseGoal.h \
    ros_lib/move_base_msgs/MoveBaseResult.h \
    ros_lib/nav_msgs/GetMap.h \
    ros_lib/nav_msgs/GetMapAction.h \
    ros_lib/nav_msgs/GetMapActionFeedback.h \
    ros_lib/nav_msgs/GetMapActionGoal.h \
    ros_lib/nav_msgs/GetMapActionResult.h \
    ros_lib/nav_msgs/GetMapFeedback.h \
    ros_lib/nav_msgs/GetMapGoal.h \
    ros_lib/nav_msgs/GetMapResult.h \
    ros_lib/nav_msgs/GetPlan.h \
    ros_lib/nav_msgs/GridCells.h \
    ros_lib/nav_msgs/MapMetaData.h \
    ros_lib/nav_msgs/OccupancyGrid.h \
    ros_lib/nav_msgs/Odometry.h \
    ros_lib/nav_msgs/Path.h \
    ros_lib/nav_msgs/SetMap.h \
    ros_lib/navfn/MakeNavPlan.h \
    ros_lib/navfn/SetCostmap.h \
    ros_lib/nodelet/NodeletList.h \
    ros_lib/nodelet/NodeletLoad.h \
    ros_lib/nodelet/NodeletUnload.h \
    ros_lib/openni2_camera/GetSerial.h \
    ros_lib/pano_ros/Pano.h \
    ros_lib/pcl_msgs/ModelCoefficients.h \
    ros_lib/pcl_msgs/PointIndices.h \
    ros_lib/pcl_msgs/PolygonMesh.h \
    ros_lib/pcl_msgs/Vertices.h \
    ros_lib/polled_camera/GetPolledImage.h \
    ros_lib/robot_pose_ekf/GetStatus.h \
    ros_lib/rocon_app_manager_msgs/Constants.h \
    ros_lib/rocon_app_manager_msgs/ErrorCodes.h \
    ros_lib/rocon_app_manager_msgs/GetRappList.h \
    ros_lib/rocon_app_manager_msgs/IncompatibleRappList.h \
    ros_lib/rocon_app_manager_msgs/Init.h \
    ros_lib/rocon_app_manager_msgs/Invite.h \
    ros_lib/rocon_app_manager_msgs/Rapp.h \
    ros_lib/rocon_app_manager_msgs/RappList.h \
    ros_lib/rocon_app_manager_msgs/StartRapp.h \
    ros_lib/rocon_app_manager_msgs/Status.h \
    ros_lib/rocon_app_manager_msgs/StopRapp.h \
    ros_lib/rocon_device_msgs/Hue.h \
    ros_lib/rocon_device_msgs/HueArray.h \
    ros_lib/rocon_device_msgs/HueState.h \
    ros_lib/rocon_interaction_msgs/ErrorCodes.h \
    ros_lib/rocon_interaction_msgs/GetInteraction.h \
    ros_lib/rocon_interaction_msgs/GetInteractions.h \
    ros_lib/rocon_interaction_msgs/GetRoles.h \
    ros_lib/rocon_interaction_msgs/Interaction.h \
    ros_lib/rocon_interaction_msgs/InteractiveClient.h \
    ros_lib/rocon_interaction_msgs/InteractiveClients.h \
    ros_lib/rocon_interaction_msgs/Pair.h \
    ros_lib/rocon_interaction_msgs/Pairing.h \
    ros_lib/rocon_interaction_msgs/RemoconStatus.h \
    ros_lib/rocon_interaction_msgs/RequestInteraction.h \
    ros_lib/rocon_interaction_msgs/SetInteractions.h \
    ros_lib/rocon_interaction_msgs/Strings.h \
    ros_lib/rocon_service_pair_msgs/TestiesPair.h \
    ros_lib/rocon_service_pair_msgs/TestiesPairRequest.h \
    ros_lib/rocon_service_pair_msgs/TestiesPairResponse.h \
    ros_lib/rocon_service_pair_msgs/TestiesRequest.h \
    ros_lib/rocon_service_pair_msgs/TestiesResponse.h \
    ros_lib/rocon_std_msgs/GetPlatformInfo.h \
    ros_lib/rocon_std_msgs/Icon.h \
    ros_lib/rocon_std_msgs/KeyValue.h \
    ros_lib/rocon_std_msgs/MasterInfo.h \
    ros_lib/rocon_std_msgs/PlatformInfo.h \
    ros_lib/rocon_std_msgs/Remapping.h \
    ros_lib/rocon_std_msgs/StringArray.h \
    ros_lib/rocon_std_msgs/Strings.h \
    ros_lib/rocon_tutorial_msgs/GetAvailableResources.h \
    ros_lib/ros/duration.h \
    ros_lib/ros/msg.h \
    ros_lib/ros/node_handle.h \
    ros_lib/ros/publisher.h \
    ros_lib/ros/service_client.h \
    ros_lib/ros/service_server.h \
    ros_lib/ros/subscriber.h \
    ros_lib/ros/time.h \
    ros_lib/rosapi/DeleteParam.h \
    ros_lib/rosapi/GetParam.h \
    ros_lib/rosapi/GetParamNames.h \
    ros_lib/rosapi/GetTime.h \
    ros_lib/rosapi/HasParam.h \
    ros_lib/rosapi/MessageDetails.h \
    ros_lib/rosapi/NodeDetails.h \
    ros_lib/rosapi/Nodes.h \
    ros_lib/rosapi/Publishers.h \
    ros_lib/rosapi/SearchParam.h \
    ros_lib/rosapi/ServiceHost.h \
    ros_lib/rosapi/ServiceNode.h \
    ros_lib/rosapi/ServiceProviders.h \
    ros_lib/rosapi/ServiceRequestDetails.h \
    ros_lib/rosapi/ServiceResponseDetails.h \
    ros_lib/rosapi/Services.h \
    ros_lib/rosapi/ServicesForType.h \
    ros_lib/rosapi/ServiceType.h \
    ros_lib/rosapi/SetParam.h \
    ros_lib/rosapi/Subscribers.h \
    ros_lib/rosapi/Topics.h \
    ros_lib/rosapi/TopicsForType.h \
    ros_lib/rosapi/TopicType.h \
    ros_lib/rosapi/TypeDef.h \
    ros_lib/rosauth/Authentication.h \
    ros_lib/roscpp/Empty.h \
    ros_lib/roscpp/GetLoggers.h \
    ros_lib/roscpp/Logger.h \
    ros_lib/roscpp/SetLoggerLevel.h \
    ros_lib/roscpp_tutorials/TwoInts.h \
    ros_lib/rosgraph_msgs/Clock.h \
    ros_lib/rosgraph_msgs/Log.h \
    ros_lib/rosgraph_msgs/TopicStatistics.h \
    ros_lib/rospy_tutorials/AddTwoInts.h \
    ros_lib/rospy_tutorials/BadTwoInts.h \
    ros_lib/rospy_tutorials/Floats.h \
    ros_lib/rospy_tutorials/HeaderString.h \
    ros_lib/rosserial_msgs/Log.h \
    ros_lib/rosserial_msgs/RequestMessageInfo.h \
    ros_lib/rosserial_msgs/RequestParam.h \
    ros_lib/rosserial_msgs/RequestServiceInfo.h \
    ros_lib/rosserial_msgs/TopicInfo.h \
    ros_lib/scheduler_msgs/CurrentStatus.h \
    ros_lib/scheduler_msgs/KnownResources.h \
    ros_lib/scheduler_msgs/Request.h \
    ros_lib/scheduler_msgs/Resource.h \
    ros_lib/scheduler_msgs/SchedulerRequests.h \
    ros_lib/sensor_msgs/BatteryState.h \
    ros_lib/sensor_msgs/CameraInfo.h \
    ros_lib/sensor_msgs/ChannelFloat32.h \
    ros_lib/sensor_msgs/CompressedImage.h \
    ros_lib/sensor_msgs/FluidPressure.h \
    ros_lib/sensor_msgs/Illuminance.h \
    ros_lib/sensor_msgs/Image.h \
    ros_lib/sensor_msgs/Imu.h \
    ros_lib/sensor_msgs/JointState.h \
    ros_lib/sensor_msgs/Joy.h \
    ros_lib/sensor_msgs/JoyFeedback.h \
    ros_lib/sensor_msgs/JoyFeedbackArray.h \
    ros_lib/sensor_msgs/LaserEcho.h \
    ros_lib/sensor_msgs/LaserScan.h \
    ros_lib/sensor_msgs/MagneticField.h \
    ros_lib/sensor_msgs/MultiDOFJointState.h \
    ros_lib/sensor_msgs/MultiEchoLaserScan.h \
    ros_lib/sensor_msgs/NavSatFix.h \
    ros_lib/sensor_msgs/NavSatStatus.h \
    ros_lib/sensor_msgs/PointCloud.h \
    ros_lib/sensor_msgs/PointCloud2.h \
    ros_lib/sensor_msgs/PointField.h \
    ros_lib/sensor_msgs/Range.h \
    ros_lib/sensor_msgs/RegionOfInterest.h \
    ros_lib/sensor_msgs/RelativeHumidity.h \
    ros_lib/sensor_msgs/SetCameraInfo.h \
    ros_lib/sensor_msgs/Temperature.h \
    ros_lib/sensor_msgs/TimeReference.h \
    ros_lib/shape_msgs/Mesh.h \
    ros_lib/shape_msgs/MeshTriangle.h \
    ros_lib/shape_msgs/Plane.h \
    ros_lib/shape_msgs/SolidPrimitive.h \
    ros_lib/smach_msgs/SmachContainerInitialStatusCmd.h \
    ros_lib/smach_msgs/SmachContainerStatus.h \
    ros_lib/smach_msgs/SmachContainerStructure.h \
    ros_lib/smart_battery_msgs/SmartBatteryStatus.h \
    ros_lib/std_msgs/Bool.h \
    ros_lib/std_msgs/Byte.h \
    ros_lib/std_msgs/ByteMultiArray.h \
    ros_lib/std_msgs/Char.h \
    ros_lib/std_msgs/ColorRGBA.h \
    ros_lib/std_msgs/Duration.h \
    ros_lib/std_msgs/Empty.h \
    ros_lib/std_msgs/Float32.h \
    ros_lib/std_msgs/Float32MultiArray.h \
    ros_lib/std_msgs/Float64.h \
    ros_lib/std_msgs/Float64MultiArray.h \
    ros_lib/std_msgs/Header.h \
    ros_lib/std_msgs/Int16.h \
    ros_lib/std_msgs/Int16MultiArray.h \
    ros_lib/std_msgs/Int32.h \
    ros_lib/std_msgs/Int32MultiArray.h \
    ros_lib/std_msgs/Int64.h \
    ros_lib/std_msgs/Int64MultiArray.h \
    ros_lib/std_msgs/Int8.h \
    ros_lib/std_msgs/Int8MultiArray.h \
    ros_lib/std_msgs/MultiArrayDimension.h \
    ros_lib/std_msgs/MultiArrayLayout.h \
    ros_lib/std_msgs/String.h \
    ros_lib/std_msgs/Time.h \
    ros_lib/std_msgs/UInt16.h \
    ros_lib/std_msgs/UInt16MultiArray.h \
    ros_lib/std_msgs/UInt32.h \
    ros_lib/std_msgs/UInt32MultiArray.h \
    ros_lib/std_msgs/UInt64.h \
    ros_lib/std_msgs/UInt64MultiArray.h \
    ros_lib/std_msgs/UInt8.h \
    ros_lib/std_msgs/UInt8MultiArray.h \
    ros_lib/std_srvs/Empty.h \
    ros_lib/std_srvs/SetBool.h \
    ros_lib/std_srvs/Trigger.h \
    ros_lib/stdr_msgs/AddCO2Source.h \
    ros_lib/stdr_msgs/AddRfidTag.h \
    ros_lib/stdr_msgs/AddSoundSource.h \
    ros_lib/stdr_msgs/AddThermalSource.h \
    ros_lib/stdr_msgs/CO2SensorMeasurementMsg.h \
    ros_lib/stdr_msgs/CO2SensorMsg.h \
    ros_lib/stdr_msgs/CO2Source.h \
    ros_lib/stdr_msgs/CO2SourceVector.h \
    ros_lib/stdr_msgs/DeleteCO2Source.h \
    ros_lib/stdr_msgs/DeleteRfidTag.h \
    ros_lib/stdr_msgs/DeleteRobotAction.h \
    ros_lib/stdr_msgs/DeleteRobotActionFeedback.h \
    ros_lib/stdr_msgs/DeleteRobotActionGoal.h \
    ros_lib/stdr_msgs/DeleteRobotActionResult.h \
    ros_lib/stdr_msgs/DeleteRobotFeedback.h \
    ros_lib/stdr_msgs/DeleteRobotGoal.h \
    ros_lib/stdr_msgs/DeleteRobotResult.h \
    ros_lib/stdr_msgs/DeleteSoundSource.h \
    ros_lib/stdr_msgs/DeleteThermalSource.h \
    ros_lib/stdr_msgs/FootprintMsg.h \
    ros_lib/stdr_msgs/KinematicMsg.h \
    ros_lib/stdr_msgs/LaserSensorMsg.h \
    ros_lib/stdr_msgs/LoadExternalMap.h \
    ros_lib/stdr_msgs/LoadMap.h \
    ros_lib/stdr_msgs/MoveRobot.h \
    ros_lib/stdr_msgs/Noise.h \
    ros_lib/stdr_msgs/RegisterGui.h \
    ros_lib/stdr_msgs/RegisterRobotAction.h \
    ros_lib/stdr_msgs/RegisterRobotActionFeedback.h \
    ros_lib/stdr_msgs/RegisterRobotActionGoal.h \
    ros_lib/stdr_msgs/RegisterRobotActionResult.h \
    ros_lib/stdr_msgs/RegisterRobotFeedback.h \
    ros_lib/stdr_msgs/RegisterRobotGoal.h \
    ros_lib/stdr_msgs/RegisterRobotResult.h \
    ros_lib/stdr_msgs/RfidSensorMeasurementMsg.h \
    ros_lib/stdr_msgs/RfidSensorMsg.h \
    ros_lib/stdr_msgs/RfidTag.h \
    ros_lib/stdr_msgs/RfidTagVector.h \
    ros_lib/stdr_msgs/RobotIndexedMsg.h \
    ros_lib/stdr_msgs/RobotIndexedVectorMsg.h \
    ros_lib/stdr_msgs/RobotMsg.h \
    ros_lib/stdr_msgs/SonarSensorMsg.h \
    ros_lib/stdr_msgs/SoundSensorMeasurementMsg.h \
    ros_lib/stdr_msgs/SoundSensorMsg.h \
    ros_lib/stdr_msgs/SoundSource.h \
    ros_lib/stdr_msgs/SoundSourceVector.h \
    ros_lib/stdr_msgs/SpawnRobotAction.h \
    ros_lib/stdr_msgs/SpawnRobotActionFeedback.h \
    ros_lib/stdr_msgs/SpawnRobotActionGoal.h \
    ros_lib/stdr_msgs/SpawnRobotActionResult.h \
    ros_lib/stdr_msgs/SpawnRobotFeedback.h \
    ros_lib/stdr_msgs/SpawnRobotGoal.h \
    ros_lib/stdr_msgs/SpawnRobotResult.h \
    ros_lib/stdr_msgs/ThermalSensorMeasurementMsg.h \
    ros_lib/stdr_msgs/ThermalSensorMsg.h \
    ros_lib/stdr_msgs/ThermalSource.h \
    ros_lib/stdr_msgs/ThermalSourceVector.h \
    ros_lib/stereo_msgs/DisparityImage.h \
    ros_lib/tf/FrameGraph.h \
    ros_lib/tf/tf.h \
    ros_lib/tf/tfMessage.h \
    ros_lib/tf/transform_broadcaster.h \
    ros_lib/tf2_msgs/FrameGraph.h \
    ros_lib/tf2_msgs/LookupTransformAction.h \
    ros_lib/tf2_msgs/LookupTransformActionFeedback.h \
    ros_lib/tf2_msgs/LookupTransformActionGoal.h \
    ros_lib/tf2_msgs/LookupTransformActionResult.h \
    ros_lib/tf2_msgs/LookupTransformFeedback.h \
    ros_lib/tf2_msgs/LookupTransformGoal.h \
    ros_lib/tf2_msgs/LookupTransformResult.h \
    ros_lib/tf2_msgs/TF2Error.h \
    ros_lib/tf2_msgs/TFMessage.h \
    ros_lib/topic_tools/DemuxAdd.h \
    ros_lib/topic_tools/DemuxDelete.h \
    ros_lib/topic_tools/DemuxList.h \
    ros_lib/topic_tools/DemuxSelect.h \
    ros_lib/topic_tools/MuxAdd.h \
    ros_lib/topic_tools/MuxDelete.h \
    ros_lib/topic_tools/MuxList.h \
    ros_lib/topic_tools/MuxSelect.h \
    ros_lib/trajectory_msgs/JointTrajectory.h \
    ros_lib/trajectory_msgs/JointTrajectoryPoint.h \
    ros_lib/trajectory_msgs/MultiDOFJointTrajectory.h \
    ros_lib/trajectory_msgs/MultiDOFJointTrajectoryPoint.h \
    ros_lib/turtle_actionlib/ShapeAction.h \
    ros_lib/turtle_actionlib/ShapeActionFeedback.h \
    ros_lib/turtle_actionlib/ShapeActionGoal.h \
    ros_lib/turtle_actionlib/ShapeActionResult.h \
    ros_lib/turtle_actionlib/ShapeFeedback.h \
    ros_lib/turtle_actionlib/ShapeGoal.h \
    ros_lib/turtle_actionlib/ShapeResult.h \
    ros_lib/turtle_actionlib/Velocity.h \
    ros_lib/turtlebot_calibration/ScanAngle.h \
    ros_lib/turtlebot_msgs/PanoramaImg.h \
    ros_lib/turtlebot_msgs/SetFollowState.h \
    ros_lib/turtlebot_msgs/TakePanorama.h \
    ros_lib/turtlesim/Color.h \
    ros_lib/turtlesim/Kill.h \
    ros_lib/turtlesim/Pose.h \
    ros_lib/turtlesim/SetPen.h \
    ros_lib/turtlesim/Spawn.h \
    ros_lib/turtlesim/TeleportAbsolute.h \
    ros_lib/turtlesim/TeleportRelative.h \
    ros_lib/uuid_msgs/UniqueID.h \
    ros_lib/visualization_msgs/ImageMarker.h \
    ros_lib/visualization_msgs/InteractiveMarker.h \
    ros_lib/visualization_msgs/InteractiveMarkerControl.h \
    ros_lib/visualization_msgs/InteractiveMarkerFeedback.h \
    ros_lib/visualization_msgs/InteractiveMarkerInit.h \
    ros_lib/visualization_msgs/InteractiveMarkerPose.h \
    ros_lib/visualization_msgs/InteractiveMarkerUpdate.h \
    ros_lib/visualization_msgs/Marker.h \
    ros_lib/visualization_msgs/MarkerArray.h \
    ros_lib/visualization_msgs/MenuEntry.h \
    ros_lib/yocs_msgs/ARPair.h \
    ros_lib/yocs_msgs/ARPairList.h \
    ros_lib/yocs_msgs/Column.h \
    ros_lib/yocs_msgs/ColumnList.h \
    ros_lib/yocs_msgs/DockingInteractorAction.h \
    ros_lib/yocs_msgs/DockingInteractorActionFeedback.h \
    ros_lib/yocs_msgs/DockingInteractorActionGoal.h \
    ros_lib/yocs_msgs/DockingInteractorActionResult.h \
    ros_lib/yocs_msgs/DockingInteractorFeedback.h \
    ros_lib/yocs_msgs/DockingInteractorGoal.h \
    ros_lib/yocs_msgs/DockingInteractorResult.h \
    ros_lib/yocs_msgs/LocalizeAction.h \
    ros_lib/yocs_msgs/LocalizeActionFeedback.h \
    ros_lib/yocs_msgs/LocalizeActionGoal.h \
    ros_lib/yocs_msgs/LocalizeActionResult.h \
    ros_lib/yocs_msgs/LocalizeFeedback.h \
    ros_lib/yocs_msgs/LocalizeGoal.h \
    ros_lib/yocs_msgs/LocalizeResult.h \
    ros_lib/yocs_msgs/NavigateToAction.h \
    ros_lib/yocs_msgs/NavigateToActionFeedback.h \
    ros_lib/yocs_msgs/NavigateToActionGoal.h \
    ros_lib/yocs_msgs/NavigateToActionResult.h \
    ros_lib/yocs_msgs/NavigateToFeedback.h \
    ros_lib/yocs_msgs/NavigateToGoal.h \
    ros_lib/yocs_msgs/NavigateToResult.h \
    ros_lib/yocs_msgs/NavigationControl.h \
    ros_lib/yocs_msgs/NavigationControlStatus.h \
    ros_lib/yocs_msgs/Table.h \
    ros_lib/yocs_msgs/TableList.h \
    ros_lib/yocs_msgs/Trajectory.h \
    ros_lib/yocs_msgs/TrajectoryList.h \
    ros_lib/yocs_msgs/Wall.h \
    ros_lib/yocs_msgs/WallList.h \
    ros_lib/yocs_msgs/Waypoint.h \
    ros_lib/yocs_msgs/WaypointList.h \
    ros_lib/yocs_msgs/WaypointListService.h \
    ros_lib/zeroconf_msgs/AddListener.h \
    ros_lib/zeroconf_msgs/AddService.h \
    ros_lib/zeroconf_msgs/DiscoveredService.h \
    ros_lib/zeroconf_msgs/ListDiscoveredServices.h \
    ros_lib/zeroconf_msgs/ListPublishedServices.h \
    ros_lib/zeroconf_msgs/Protocols.h \
    ros_lib/zeroconf_msgs/PublishedService.h \
    ros_lib/zeroconf_msgs/RemoveListener.h \
    ros_lib/zeroconf_msgs/RemoveService.h \
    ros_lib/ros.h \
    ros_lib/WindowsSocket.h

INCLUDEPATH += $$PWD/ros_lib
DEPENDPATH += $$PWD/ros_lib
